packages:
  - apps/*
  - packages/*

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@tailwindcss/oxide': true
  '@node-rs/argon2': true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
  '@sentry-internal/node-cpu-profiler': true
  '@sentry/cli': true
  '@parcel/watcher': true
  '@swc/core': true
  protobufjs: true

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - "@scarf/scarf"
  - "@tailwindcss/oxide"
  - "@node-rs/argon2"
  - esbuild
  - msw
  - prisma
  - sharp
  - unrs-resolver
  - "@sentry-internal/node-cpu-profiler"
  - "@sentry/cli"
  - "@parcel/watcher"
  - "@swc/core"
  - protobufjs
